# Generated by Django 5.2.16 on 2026-07-18 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'technicians',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email Google (identifiant de connexion)', max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'venues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('audio', 'Audio'), ('eclairage', 'Éclairage'), ('video', 'Vidéo'), ('reseau', 'Réseau'), ('rigging', 'Rigging'), ('mobilier', 'Mobilier'), ('decor', 'Décor'), ('costumes', 'Costumes'), ('autre', 'Autre')], max_length=20)),
                ('ownership_status', models.CharField(choices=[('owned', 'Propriété'), ('rental', 'Location')], default='owned', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, help_text="Département responsable d'apporter ce matériel sur le lieu du spectacle", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.department')),
                ('parent_material', models.ForeignKey(blank=True, help_text="Matériel parent (ex. 'Kit Audio' est parent de 'Micro sans fil')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='inventory.material')),
                ('venue', models.ForeignKey(blank=True, help_text='Lieu physique où le matériel est entreposé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.venue')),
            ],
            options={
                'db_table': 'materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('rehearsal', 'Répétition'), ('performance', 'Représentation')], max_length=15)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('buffer_before_minutes', models.PositiveIntegerField(default=60)),
                ('buffer_after_minutes', models.PositiveIntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='inventory.venue')),
            ],
            options={
                'db_table': 'shows',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ShowMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rental', models.BooleanField(default=False)),
                ('rental_vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_materials', to='inventory.material')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_materials', to='inventory.show')),
            ],
            options={
                'db_table': 'show_materials',
                'ordering': ['show'],
                'unique_together': {('show', 'material')},
            },
        ),
        migrations.CreateModel(
            name='ShowTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_technicians', to='inventory.show')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_technicians', to='inventory.technician')),
            ],
            options={
                'db_table': 'show_technicians',
                'ordering': ['show'],
                'unique_together': {('show', 'technician')},
            },
        ),
    ]
