# Generated by Django 5.2.16 on 2026-07-18 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='django_user',
            field=models.OneToOneField(blank=True, help_text="Compte django.contrib.auth.User associé, créé automatiquement par django-allauth lors du premier login Google réussi. Permet de retrouver ce profil applicatif depuis la session Django authentifiée. Nullable : distinct du superutilisateur Django (/admin/), qui n'a pas besoin de ce lien.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
