# Generated by Django 5.2.16 on 2026-07-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_user_django_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_storage',
            field=models.BooleanField(default=False, help_text="Lieu d'entreposage (entrepôt) plutôt qu'un vrai lieu de spectacle. Le matériel assigné (via show_materials) à un Show dont le venue a is_storage=True est considéré disponible et ignoré par la détection de conflits — voir conflicts.py."),
        ),
        migrations.AlterField(
            model_name='show',
            name='event_type',
            field=models.CharField(choices=[('rehearsal', 'Répétition'), ('performance', 'Représentation'), ('storage', 'Entreposage')], max_length=15),
        ),
    ]
