# Generated by Django 5.2.16 on 2026-07-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_venue_is_storage_alter_show_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('delivery', 'Livraison'), ('pickup', 'Ramassage')], max_length=10)),
                ('scheduled_datetime', models.DateTimeField(help_text='Heure prévue du déplacement.')),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60, help_text='Durée estimée du déplacement (trajet + chargement/déchargement).')),
                ('notes', models.TextField(blank=True)),
                ('destination_venue', models.ForeignKey(help_text="Lieu d'arrivée (souvent le lieu du spectacle pour une livraison).", on_delete=django.db.models.deletion.PROTECT, related_name='transports_to', to='inventory.venue')),
                ('origin_venue', models.ForeignKey(help_text='Lieu de départ (souvent un entrepôt pour une livraison).', on_delete=django.db.models.deletion.PROTECT, related_name='transports_from', to='inventory.venue')),
                ('show', models.ForeignKey(help_text='Spectacle desservi par ce déplacement.', on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='inventory.show')),
                ('technician', models.ForeignKey(blank=True, help_text='Technicien assigné au déplacement (peut être laissé vide tant que non confirmé).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='inventory.technician')),
            ],
            options={
                'db_table': 'transports',
                'ordering': ['scheduled_datetime'],
            },
        ),
    ]
