# Generated by Django 5.2.16 on 2026-07-18 12:32

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_buffer_before_minutes', models.PositiveIntegerField(default=60, help_text="Valeur proposée par défaut pour buffer_before_minutes à la création d'un Show.")),
                ('default_buffer_after_minutes', models.PositiveIntegerField(default=60, help_text="Valeur proposée par défaut pour buffer_after_minutes à la création d'un Show.")),
                ('default_transport_duration_minutes', models.PositiveIntegerField(default=60, help_text="Valeur proposée par défaut pour estimated_duration_minutes à la création d'un Transport.")),
                ('date_format', models.CharField(choices=[('DMY', 'JJ/MM/AAAA'), ('MDY', 'MM/DD/YYYY')], default='DMY', max_length=3)),
                ('time_format', models.CharField(choices=[('24h', '24 heures'), ('12h', '12 heures (AM/PM)')], default='24h', max_length=3)),
            ],
            options={
                'verbose_name': 'Réglages',
                'verbose_name_plural': 'Réglages',
                'db_table': 'settings',
            },
        ),
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Coordonnée GPS (ex. copiée depuis Google Maps) — utilisée avec longitude pour estimer automatiquement les temps de trajet des Transport via l'API Google Routes (voir inventory/maps.py).", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordonnée GPS — voir latitude.', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='buffer_after_minutes',
            field=models.PositiveIntegerField(default=inventory.models._default_buffer_after_minutes),
        ),
        migrations.AlterField(
            model_name='show',
            name='buffer_before_minutes',
            field=models.PositiveIntegerField(default=inventory.models._default_buffer_before_minutes),
        ),
        migrations.AlterField(
            model_name='transport',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=inventory.models._default_transport_duration_minutes, help_text="Durée estimée du déplacement (trajet + chargement/déchargement). Pré-remplie automatiquement via l'API Google Routes si les deux venues ont des coordonnées GPS (voir TransportSerializer et inventory/maps.py) ; sinon, valeur par défaut tirée de Settings."),
        ),
    ]
