# Generated by Django 5.2.16 on 2026-07-18 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_settings_venue_latitude_venue_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(default='#64748B', help_text="Code hexadécimal complet (#RRGGBB) utilisé pour identifier visuellement ce département dans l'app.", max_length=7, validators=[django.core.validators.RegexValidator(message='La couleur doit être un code hexadécimal complet, ex. #3B82F6.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
