# Generated by Django 5.2.16 on 2026-07-19 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_department_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text="Quantité totale possédée de ce matériel identique (ex. 20 rallonges électriques). Permet d'assigner une partie seulement de l'inventaire à un spectacle (voir ShowMaterial.quantity) sans créer un item par unité physique. Doit rester à 1 pour un matériel qui fait partie d'une hiérarchie kit — parent_material renseigné, ou qui a lui-même des composants (imposé par MaterialSerializer.validate(), pas ici : un kit reste une unité conceptuelle unique, ajouté le 2026-07-19).", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='showmaterial',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantité de ce matériel assignée à ce spectacle (ex. 5 des 20 rallonges en inventaire). Voir Material.quantity et conflicts.py pour le calcul de capacité (ajouté le 2026-07-19).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
