# Generated by Django 5.2.16 on 2026-07-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_material_quantity_showmaterial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Permet de désactiver un matériel qu'on n'utilise plus (ex. un vieux rideau) sans le supprimer — masqué des listes d'inventaire par défaut (voir MaterialViewSet), mais reste consultable individuellement et dans l'historique des assignations existantes. Ajouté le 2026-07-19."),
        ),
    ]
