# Generated by Django 5.2.16 on 2026-07-19 04:31
#
# Note (revue de code, 2026-07-19) : les `default=1` ci-dessous sur les 4 champs
# `project` sont des valeurs "one-off" purement techniques, exigées par Django
# pour ajouter un FK NOT NULL — elles ne sont JAMAIS lues par l'application
# (`preserve_default=False` : le modèle Python n'a pas de vrai défaut). Sûr
# uniquement parce que `venues`/`materials`/`technicians`/`shows` étaient
# confirmées vides en prod par Samuel au moment de cette migration ; sur une
# base déjà peuplée, `migrate` échouerait (IntegrityError FK sur MySQL,
# éventuellement silencieux sur SQLite) faute d'un vrai `Project` id=1.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_material_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, help_text='Compagnie ou organisation cliente, si pertinent (ex. une compagnie de danse, un musée).', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('archived', 'Archivé')], default='active', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='project',
            field=models.ForeignKey(default=1, help_text='Production à laquelle ce matériel appartient — voir Project.', on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='inventory.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='project',
            field=models.ForeignKey(default=1, help_text='Production à laquelle ce spectacle appartient — voir Project. Doit correspondre au projet de `venue`.', on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='inventory.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='project',
            field=models.ForeignKey(default=1, help_text='Production à laquelle ce technicien appartient — voir Project.', on_delete=django.db.models.deletion.PROTECT, related_name='technicians', to='inventory.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='project',
            field=models.ForeignKey(default=1, help_text='Production à laquelle ce lieu appartient — voir Project.', on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='inventory.project'),
            preserve_default=False,
        ),
    ]
