# Generated by Django 5.2.16 on 2026-07-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_project_material_project_show_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='code',
            field=models.CharField(blank=True, help_text="Code court (jusqu'à 4 caractères, ex. CHAP pour Chapelle) saisi à la création du lieu — sert d'identifiant rapide, notamment pour afficher le départ/arrivée d'un Transport de façon compacte (voir TransportSerializer). Normalisé en majuscules à l'enregistrement. Unique par projet si renseigné (validé par VenueSerializer, pas en base — plusieurs lieux sans code coexistent normalement). Ajouté le 2026-07-19.", max_length=4),
        ),
    ]
