# Generated by Django 5.2.16 on 2026-07-24 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_venue_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantité de ce matériel transportée par ce déplacement (ex. 8 des 20 rallonges en inventaire). Voir Material.quantity et transport_coherence.py pour le suivi des emplacements.', validators=[django.core.validators.MinValueValidator(1)])),
                ('material', models.ForeignKey(help_text='Matériel transporté.', on_delete=django.db.models.deletion.CASCADE, related_name='transport_materials', to='inventory.material')),
                ('transport', models.ForeignKey(help_text='Déplacement qui transporte ce matériel.', on_delete=django.db.models.deletion.CASCADE, related_name='transport_materials', to='inventory.transport')),
            ],
            options={
                'db_table': 'transport_materials',
                'ordering': ['transport'],
                'unique_together': {('transport', 'material')},
            },
        ),
    ]
