# Generated by Django 5.2.16 on 2026-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_transportmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='status',
            field=models.CharField(
                choices=[('confirmed', 'Confirmé'), ('to_approve', 'À approuver')],
                default='confirmed',
                help_text=(
                    "Cycle de vie du déplacement. 'confirmed' : créé/complété par l'utilisateur, participe à "
                    "la timeline de position et à la détection de conflit du technicien. 'to_approve' : "
                    "proposition générée automatiquement (voir transport_autogen.py) quand du matériel est "
                    "requis à un lieu où rien ne l'amène — pré-remplie (lieux + matériel) mais incomplète "
                    "(heure/technicien à saisir), affichée en orange. Une proposition NE compte PAS comme "
                    "livraison tant qu'elle n'est pas confirmée. Ajouté le 2026-07-24."
                ),
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name='transport',
            name='scheduled_datetime',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text=(
                    "Heure prévue du déplacement. Nullable depuis le 2026-07-24 : une proposition auto "
                    "(status='to_approve') n'a pas encore d'heure tant que l'utilisateur ne l'a pas "
                    "complétée. Obligatoire pour un déplacement 'confirmed' (imposé par TransportSerializer)."
                ),
            ),
        ),
    ]
