# Generated by Django 5.2.16 on 2026-07-29 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_transport_status_scheduled_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
