# Generated by Django 5.2.16 on 2026-07-31 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_transport_technicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='parent_show',
            field=models.ForeignKey(blank=True, help_text="Événement principal auquel ce bloc est rattaché — montage ou répétition en amont, démontage en aval (ajouté le 2026-07-31). Un bloc rattaché est un `Show` à part entière : il a son lieu, ses horaires, son matériel et ses techniciens, et participe à la détection de conflits comme n'importe quel événement. Un seul niveau — un bloc ne peut pas lui-même en avoir (validé par ShowSerializer). CASCADE : supprimer l'événement principal supprime ses blocs, ils n'ont pas de sens seuls.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='inventory.show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='event_type',
            field=models.CharField(choices=[('rehearsal', 'Répétition'), ('performance', 'Représentation'), ('storage', 'Entreposage'), ('setup', 'Montage'), ('teardown', 'Démontage')], max_length=15),
        ),
    ]
