# Generated by Django 5.2.16 on 2026-08-01 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_show_phases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='parent_show',
            field=models.ForeignKey(blank=True, help_text="Événement principal auquel ce bloc est rattaché — montage ou répétition en amont, démontage en aval (ajouté le 2026-07-31). Un bloc rattaché est un `Show` à part entière : il a son lieu, ses horaires, et participe à la détection de conflits comme n'importe quel événement. Ses ressources dépendent de son type — voir `INHERITING_PHASE_TYPES` et `inherits_resources`. Un seul niveau — un bloc ne peut pas lui-même en avoir (validé par ShowSerializer). CASCADE : supprimer l'événement principal supprime ses blocs, ils n'ont pas de sens seuls.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='inventory.show'),
        ),
    ]
