# Generated by Django 5.2.16 on 2026-08-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_show_parent_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
