# Generated by Django 5.2.16 on 2026-08-02 03:39
"""Migration de schéma pour l'accès multi-tenant par projet (2026-08-02).

Ajoute `users.is_staff_global` (accès de dépannage plateforme, court-circuite
le contrôle par projet) et crée `project_memberships` (voir
`ProjectMembership`, models.py — rôles `owner`/`editor`/`viewer` par projet).
Migration de DONNÉES associée : `0020_project_access_data.py` (staff
existants, Samuel owner des projets préexistants).
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_show_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff_global',
            field=models.BooleanField(default=False, help_text="Accès de dépannage/support réservé à l'exploitant de la plateforme (Samuel), ajouté le 2026-08-02 quand l'app est devenue multi-tenant (abonnements vendus à d'autres directeurs techniques/compagnies). Distinct de `role` ci-dessus, qui reste un rôle global purement d'affichage côté frontend (UtilisateursView.vue) et ne gate rien côté API. `is_staff_global` COURT-CIRCUITE entièrement le contrôle d'accès par projet (voir `ProjectMembership` et `HasProjectAccess` dans permissions.py) — utile pour le support/dépannage sur les projets clients une fois l'outil vendu. Ne pas confondre avec un rôle `owner` de `ProjectMembership`, qui ne donne accès qu'à SES projets."),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, help_text="Utilisateur qui a envoyé l'invitation — nul pour l'appartenance créée automatiquement (ex. le créateur d'un projet).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to='inventory.user')),
                ('project', models.ForeignKey(help_text='Projet auquel cet accès donne droit.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='inventory.project')),
                ('user', models.ForeignKey(help_text="Compte applicatif qui reçoit l'accès (jamais nullable — voir le flux d'invitation ci-dessus).", on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='inventory.user')),
            ],
            options={
                'db_table': 'project_memberships',
                'ordering': ['project_id', 'role'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
