# Generated by Django 5.2.16 on 2026-08-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_project_access_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='color',
            field=models.CharField(blank=True, default='', help_text="Couleur d'affichage optionnelle pour les bandes représentant ce lieu (Parcours Matériel) — chaîne CSS libre (ex. oklch(...)). Vide par défaut : la couleur reste générée automatiquement (palette cyclée par ordre d'apparition, voir ParcoursMaterielView.vue) — ce champ ne fait que permettre de la fixer manuellement pour un lieu donné. Ajouté le 2026-08-02 à la demande de Samuel.", max_length=64),
        ),
    ]
