# Generated by Django 5.2.16 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_venue_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_kit_parent',
            field=models.BooleanField(default=False, help_text="Active ce matériel comme parent de kit possible — limite la liste affichée dans le sélecteur « Fait partie du kit » d'un autre matériel (MaterialSerializer.validate_parent_material refuse un parent qui n'a pas ce drapeau) et fait apparaître sur sa fiche une section pour lui ajouter directement des composants. Un matériel à quantity > 1 ne peut pas être marqué ainsi (voir MaterialSerializer.validate(), même esprit que la contrainte sur quantity ci-dessous). Ajouté le 2026-08-02 à la demande de Samuel — décision actée avec lui : pas de bascule automatique sur les kits existants (déjà des composants), à réactiver manuellement au cas par cas."),
        ),
    ]
