# Generated by Django 5.2.16 on 2026-08-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_material_is_kit_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='event_color_performance',
            field=models.CharField(default='oklch(0.75 0.13 320)', help_text='Couleur du type de spectacle Représentation.', max_length=64),
        ),
        migrations.AddField(
            model_name='settings',
            name='event_color_rehearsal',
            field=models.CharField(default='oklch(0.8 0.13 85)', help_text='Couleur du type de spectacle Répétition.', max_length=64),
        ),
        migrations.AddField(
            model_name='settings',
            name='event_color_setup',
            field=models.CharField(default='oklch(0.75 0.13 165)', help_text='Couleur du type de bloc Montage.', max_length=64),
        ),
        migrations.AddField(
            model_name='settings',
            name='event_color_storage',
            field=models.CharField(default='rgba(var(--fg-rgb),.6)', help_text='Couleur du type de spectacle Entreposage.', max_length=64),
        ),
        migrations.AddField(
            model_name='settings',
            name='event_color_teardown',
            field=models.CharField(default='oklch(0.7 0.11 255)', help_text='Couleur du type de bloc Démontage.', max_length=64),
        ),
        migrations.AddField(
            model_name='settings',
            name='transport_color',
            field=models.CharField(default='oklch(0.64 0.21 340)', help_text='Couleur des déplacements confirmés (Dashboard, Parcours Matériel).', max_length=64),
        ),
    ]
