# Generated by Django 5.2.16 on 2026-08-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_settings_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='event_type_order',
            field=models.CharField(blank=True, default='', help_text="Ordre d'affichage des types, séparés par des virgules (ex. 'rehearsal,setup,performance,teardown,transport,storage'). Vide = ordre par défaut.", max_length=200),
        ),
    ]
