# Generated by Django 5.2.16 on 2026-08-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_project_cascade_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='venue',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text="Rang d'affichage dans le projet (0 = non classé). À égalité, le tri se fait par nom — c'est l'ordre par défaut."),
        ),
    ]
