"""Liens publics de rapport (`ReportShare`) — chantier des sorties de
rapports, 2026-08-08.

Table seule, aucune donnée existante touchée : rien à rétro-remplir, aucun
champ retiré ailleurs. Réversible sans perte pour tout ce qui précède —
seuls les liens émis après le déploiement disparaîtraient à un rollback, et
avec eux les QR déjà imprimés.

Les contraintes déclarées ici portent deux décisions structurantes (voir le
docstring de `ReportShare`) : une seule cible cohérente avec `kind`, et un
seul partage ACTIF par cible — c'est cette dernière qui garantit qu'une
feuille réimprimée porte le même QR que celle distribuée le mois dernier.
"""

# Generated by Django 5.2.16 on 2026-08-08 14:57

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_trucks"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("transport", "Fiche de transport"),
                            ("show", "Fiche spectacle"),
                            ("technician", "Parcours technicien"),
                            ("day", "Horaire de la journée"),
                        ],
                        help_text="Type de sortie — détermine laquelle des cibles ci-dessous est renseignée.",
                        max_length=12,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=inventory.models.generate_share_token,
                        editable=False,
                        help_text="Secret d'URL — voir generate_share_token(). Jamais réémis pour une même cible.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        blank=True,
                        help_text="Journée partagée (kind='day') — l'horaire de tout le projet ce jour-là.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expiration optionnelle. Laissé vide par défaut : une feuille de tournée doit rester lisible pendant toute la production, et une date d'expiration mal choisie transforme un QR en cul-de-sac au pire moment (sur le quai, sans réseau pour appeler Samuel).",
                        null=True,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Révocation manuelle — coupe l'accès immédiatement, y compris pour les copies papier déjà distribuées.",
                        null=True,
                    ),
                ),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre de consultations. Sert à répondre à « est-ce que le monde scanne vraiment le code ? » et à repérer un lien anormalement sollicité. Incrémenté en base via F() — voir public_views.py.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Compte qui a émis le lien. SET_NULL : retirer une personne du projet ne doit pas casser les feuilles déjà imprimées.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_shares",
                        to="inventory.user",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Production à laquelle ce partage appartient. Redondant avec le projet de la cible pour les trois types qui en ont une, mais indispensable pour `day` (qui n'a pas de FK) et pour lister les partages d'un projet sans quatre jointures.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_shares",
                        to="inventory.project",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        blank=True,
                        help_text="Spectacle partagé (kind='show').",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_shares",
                        to="inventory.show",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technicien dont le parcours est partagé (kind='technician').",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_shares",
                        to="inventory.technician",
                    ),
                ),
                (
                    "transport",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tournée partagée (kind='transport').",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_shares",
                        to="inventory.transport",
                    ),
                ),
            ],
            options={
                "db_table": "report_shares",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("day__isnull", True),
                                ("kind", "transport"),
                                ("show__isnull", True),
                                ("technician__isnull", True),
                                ("transport__isnull", False),
                            ),
                            models.Q(
                                ("day__isnull", True),
                                ("kind", "show"),
                                ("show__isnull", False),
                                ("technician__isnull", True),
                                ("transport__isnull", True),
                            ),
                            models.Q(
                                ("day__isnull", True),
                                ("kind", "technician"),
                                ("show__isnull", True),
                                ("technician__isnull", False),
                                ("transport__isnull", True),
                            ),
                            models.Q(
                                ("day__isnull", False),
                                ("kind", "day"),
                                ("show__isnull", True),
                                ("technician__isnull", True),
                                ("transport__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="report_share_cible_coherente",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("transport",),
                        name="report_share_unique_actif_transport",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("show",),
                        name="report_share_unique_actif_show",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("technician",),
                        name="report_share_unique_actif_technician",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("project", "day"),
                        name="report_share_unique_actif_day",
                    ),
                ],
            },
        ),
    ]
